name: Build and Release GeyserBlockJavaPlayers

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build all modules with Maven
        run: mvn clean package -B

      - name: Upload artifacts (CI only)
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: GeyserBlockJavaPlayers
          path: |
            spigot/target/GeyserBlockJavaPlayers*.jar
            bungeecord/target/GeyserBlockJavaPlayers*.jar
            velocity/target/GeyserBlockJavaPlayers*.jar

      - name: Create GitHub Release (on tag)
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            spigot/target/GeyserBlockJavaPlayers*.jar
            bungeecord/target/GeyserBlockJavaPlayers*.jar
            velocity/target/GeyserBlockJavaPlayers*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
